modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]] 
modId="nuclearcraft"
version="${version}"
displayName="Nuclearcraft Neoteric" 
logoFile="logo.png"
credits="tomdodd4598, Lach01298"
authors="igentuman"
description='''
A complex nuclear engineering mod for Minecraft
'''

[[dependencies.nuclearcraft]]
modId="forge" 
mandatory=true 
versionRange="[43,)" 
ordering="NONE"
side="BOTH"
[[dependencies.nuclearcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
