package igentuman.nc.network;

import igentuman.nc.util.ModUtil;
import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;
import net.neoforged.neoforge.network.registration.PayloadRegistrar;

import static igentuman.nc.NuclearCraft.MODID;

/** Registers all mod network payloads and their handlers with the payload registrar. */
public class Networking {

    public static void registerPayloads(RegisterPayloadHandlersEvent event) {
        PayloadRegistrar registrar = event.registrar(MODID).versioned("1");
        registrar.playToServer(
                PacketSideConfigToggle.TYPE,
                PacketSideConfigToggle.STREAM_CODEC,
                PacketSideConfigToggle::handle
        );
        registrar.playToServer(
                PacketRedstoneModeCycle.TYPE,
                PacketRedstoneModeCycle.STREAM_CODEC,
                PacketRedstoneModeCycle::handle
        );
        registrar.playToServer(
                PacketProcessorButtonPress.TYPE,
                PacketProcessorButtonPress.STREAM_CODEC,
                PacketProcessorButtonPress::handle
        );
        registrar.playToServer(
                PacketPipeConnectorButton.TYPE,
                PacketPipeConnectorButton.STREAM_CODEC,
                PacketPipeConnectorButton::handle
        );
        registrar.playToServer(
                PacketFissionToggleMode.TYPE,
                PacketFissionToggleMode.STREAM_CODEC,
                PacketFissionToggleMode::handle
        );
        registrar.playToServer(
                PacketHeatExchangerToggleRadiators.TYPE,
                PacketHeatExchangerToggleRadiators.STREAM_CODEC,
                PacketHeatExchangerToggleRadiators::handle
        );
        registrar.playToServer(
                PacketFusionAmplificationAdjust.TYPE,
                PacketFusionAmplificationAdjust.STREAM_CODEC,
                PacketFusionAmplificationAdjust::handle
        );
        registrar.playToServer(
                PacketKugelblitzSliderAdjust.TYPE,
                PacketKugelblitzSliderAdjust.STREAM_CODEC,
                PacketKugelblitzSliderAdjust::handle
        );
        registrar.playToServer(
                PacketMsrRateAdjust.TYPE,
                PacketMsrRateAdjust.STREAM_CODEC,
                PacketMsrRateAdjust::handle
        );
        registrar.playToServer(
                PacketMsrVoidFuel.TYPE,
                PacketMsrVoidFuel.STREAM_CODEC,
                PacketMsrVoidFuel::handle
        );
        registrar.playToServer(
                PacketExplBurst.TYPE,
                PacketExplBurst.STREAM_CODEC,
                PacketExplBurst::handle
        );
        registrar.playToServer(
                PacketCrafterExtract.TYPE,
                PacketCrafterExtract.STREAM_CODEC,
                PacketCrafterExtract::handle
        );
        registrar.playToServer(
                PacketCrafterInsert.TYPE,
                PacketCrafterInsert.STREAM_CODEC,
                PacketCrafterInsert::handle
        );
        registrar.playToServer(
                PacketCrafterFillGrid.TYPE,
                PacketCrafterFillGrid.STREAM_CODEC,
                PacketCrafterFillGrid::handle
        );
        registrar.playToServer(
                PacketEncoderFillGrid.TYPE,
                PacketEncoderFillGrid.STREAM_CODEC,
                PacketEncoderFillGrid::handle
        );
        registrar.playToServer(
                PacketCancelCraft.TYPE,
                PacketCancelCraft.STREAM_CODEC,
                PacketCancelCraft::handle
        );
        registrar.playToServer(
                PacketTerminalCraft.TYPE,
                PacketTerminalCraft.STREAM_CODEC,
                PacketTerminalCraft::handle
        );
        registrar.playToServer(
                PacketCrafterOpenEncoder.TYPE,
                PacketCrafterOpenEncoder.STREAM_CODEC,
                PacketCrafterOpenEncoder::handle
        );
        if (ModUtil.isAe2Loaded()) {
            registrar.playToServer(
                    PacketAE2PatternTransfer.TYPE,
                    PacketAE2PatternTransfer.STREAM_CODEC,
                    PacketAE2PatternTransfer::handle
            );
        }
        registrar.playToClient(
                PacketMultiblockFormed.TYPE,
                PacketMultiblockFormed.STREAM_CODEC,
                PacketMultiblockFormed::handle
        );
        registrar.playToClient(
                PacketMultiblockBroken.TYPE,
                PacketMultiblockBroken.STREAM_CODEC,
                PacketMultiblockBroken::handle
        );
        registrar.playToClient(
                PacketBombDetonationStart.TYPE,
                PacketBombDetonationStart.STREAM_CODEC,
                PacketBombDetonationStart::handle
        );
        registrar.playToClient(
                PacketSyncContainerInventory.TYPE,
                PacketSyncContainerInventory.STREAM_CODEC,
                PacketSyncContainerInventory::handle
        );
        registrar.playToClient(
                PacketCraftDenied.TYPE,
                PacketCraftDenied.STREAM_CODEC,
                PacketCraftDenied::handle
        );
        registrar.playToServer(
                PacketQ36Fire.TYPE,
                PacketQ36Fire.STREAM_CODEC,
                PacketQ36Fire::handle
        );
        registrar.playToServer(
                PacketSaveFissionDesign.TYPE,
                PacketSaveFissionDesign.STREAM_CODEC,
                PacketSaveFissionDesign::handle
        );
        registrar.playToServer(
                PacketLoadFissionDesign.TYPE,
                PacketLoadFissionDesign.STREAM_CODEC,
                PacketLoadFissionDesign::handle
        );
        registrar.playToServer(
                PacketBuildMultiblock.TYPE,
                PacketBuildMultiblock.STREAM_CODEC,
                PacketBuildMultiblock::handle
        );
        registrar.playToClient(
                PacketFissionDesignData.TYPE,
                PacketFissionDesignData.STREAM_CODEC,
                PacketFissionDesignData::handle
        );
        registrar.playToClient(
                PacketQ36BeamFx.TYPE,
                PacketQ36BeamFx.STREAM_CODEC,
                PacketQ36BeamFx::handle
        );
    }
}
